# Generated by Django 5.0.1 on 2024-01-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hsk_link_academy_hsk_link_dig_hsk_link_pandarin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsk',
            name='link_audio2',
            field=models.TextField(default='/', max_length=10000),
        ),
        migrations.AddField(
            model_name='hsk',
            name='link_audio3',
            field=models.TextField(default='/', max_length=10000),
        ),
        migrations.AddField(
            model_name='hsk',
            name='link_reading2',
            field=models.TextField(default='/', max_length=10000),
        ),
        migrations.AddField(
            model_name='hsk',
            name='link_reading3',
            field=models.TextField(default='/', max_length=10000),
        ),
        migrations.AlterField(
            model_name='hsk',
            name='link_audio',
            field=models.TextField(default='/', max_length=10000),
        ),
        migrations.AlterField(
            model_name='hsk',
            name='link_reading',
            field=models.TextField(default='/', max_length=10000),
        ),
    ]
