# Generated by Django 5.0.1 on 2024-02-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hsk_link_writing_hsk_link_writing2_hsk_link_writing3'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfirebase',
            name='history',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
