# Generated by Django 5.0.1 on 2024-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userfirebase_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfirebase',
            old_name='history',
            new_name='historyUrl',
        ),
        migrations.AddField(
            model_name='userfirebase',
            name='historyDescribe',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='userfirebase',
            name='historyTitle',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
